### PR TITLE
Add modal options

### LINKED ISSUE #58: Avoid the dialog to close when clicked outside...

### PR DESCRIPTION
**Pull request by Deuteu**
Based on bootsrap modal options

Should resolve #58

### CODE REVIEW

**Comment by mnapoli** [comment]
Awesome thanks

**Comment by Deuteu** [comment]
Just realized I forgot to update options available in comment.
[jquery.confirm.js#L18](https://github.com/myclabs/jquery.confirm/blob/master/jquery.confirm.js#L18)
[jquery.confirm.js#L40](https://github.com/myclabs/jquery.confirm/blob/master/jquery.confirm.js#L40)

**Comment by mnapoli** [comment]
:+1: I've updated the docs

**Comment by Deuteu** [comment]
And you could also close #56 given it is included here.

**Comment by Deuteu** [comment]
I deleted by mistake my branch, PR was allready merged so I guess it's not a problem but tell me if you need it again.

**Comment by mnapoli** [comment]
:+1: I'm closing #56

**Pull request merged**
