### PR TITLE
add form submit option

### PR DESCRIPTION
**Pull request by alemata**
This is useful when you want to just submit a form you already have in your application. 
This allows you to have a form with different options (method, csrf_token) being able to confirm the action.

### CODE REVIEW

**Comment by mnapoli** [comment]
Thanks, this is a good idea!

I'm a little confused by the documentation/how to use it:

> If true, it submit the form target element.

How would you use your new feature? Do you have a small example?

**Comment by alemata** [comment]
yes, sorry, that was a really bad documentation addition :-1: 

here is an example: 
````html
<form action="/entities/226728/accounts/207720" class="confirm" data-submit-form="true" method="post">
  <input name="_method" type="hidden" value="DELETE">
  <input name="_csrf_token" type="hidden"  value="L0dGSGYhA0JBHWARY2ZrAhksNgEPAAAAzst1Rrtq7EURUUYfuNDOBQ==">
  <input type="submit" value="Remove">
</form>
````

So when you confirm the form would be submitted.

**Comment by alemata** [comment]
@mnapoli Hi! I need an update here
Are you going to merge this? 
was that clear enought?

**Comment by mnapoli** [comment]
Sorry I let this slide by and forgot to come back later, thanks for the reminder.

Merging!

**Comment by mnapoli** [comment]
I have tagged 2.6.0: https://github.com/myclabs/jquery.confirm/releases

Thank you!

**Comment by alemata** [comment]
great! thanks! :+1:

**Pull request merged**
