### PR TITLE
Deal with no argument passed.

### PR DESCRIPTION
**Pull request by Deuteu**
cf commit description

### CODE REVIEW

**Comment by mnapoli** [comment]
Just to be sure I understand: if someone calls `confirm()` with no option then silently nothing will happen? It might be hard to understand/debug.

**Comment by Deuteu** [comment]
You understood the behaviour.
You prefer to throw error ?

If error thrown would be great to also do it for the presence of `confirmation-modal` no ?

**Comment by mnapoli** [comment]
Yes in case there's something wrong there should be an error IMO

> If error thrown would be great to also do it for the presence of confirmation-modal no ?

I'm not sure I understand?

**Comment by Deuteu** [comment]
If we throw error for the absence of options because it easier to track for debug, it seems logical to me to also not exit whitout error when there is allready a `.confirmation-modal` (current behaviour at [jquery.confirm.js#L45](https://github.com/myclabs/jquery.confirm/blob/master/jquery.confirm.js#L45)).

This is not the purpose of that PR but more a proposition for a common behaviour for the different premature exits if we introduce error in this case.

**Comment by Deuteu** [comment]
So for this PR it's should be good to go now.

I might do an other one for what I was talking about earlier.

**Comment by mnapoli** [comment]
:+1:

**Pull request merged**
