### PR TITLE
Change name to match bower registry

### PR DESCRIPTION
**Pull request by OmgImAlexis**

### CODE REVIEW

**Comment by mnapoli** [comment]
Thank you

**Comment by OmgImAlexis** [comment]
@mnapoli does the version need a bump?
````
bower jquery-confirm#*        mismatch Version declared in the json (2.3.1) is different than the resolved one (2.5.1)
````

**Comment by mnapoli** [comment]
Will it work if I remove the version from bower.json? Keeping it up to date seems very boring.

**Comment by OmgImAlexis** [comment]
I'm not sure. I'm guessing if you remove it then it'll just default to "latest" and people won't be able to install an older version.

**Comment by mnapoli** [comment]
Let's try with this one: https://github.com/myclabs/jquery.confirm/releases/tag/2.5.2

**Pull request merged**
